version: "3.8"
services:
  api:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"