groups:
  - name: opsai_alerts
    rules:
      - alert: HighErrorRate
        expr: |
          increase(opsai_requests_total{http_status=~"5.."}[5m])
          /
          increase(opsai_requests_total[5m])
          > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on OpsAI API"
          description: "More than 5% of requests are 5xx over the last 5m"

      - alert: HighLatency
        expr: |
          histogram_quantile(0.9,
            sum(rate(opsai_request_latency_seconds_bucket[5m]))
            by (le, method, endpoint)
          )
          > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High 90th‑percentile latency"
          description: "90th percentile latency > 1s for {{ $labels.endpoint }} over last 5m"
